version: '2'

services:
  helpy:
    build: .
    restart: always
    volumes:
      - $BASE_PATH/data:/helpy/public
    env_file: stack.env
    depends_on:
      - helpy-db
    ports: 
      - "3000:3000"
  helpy-db:
    image: postgres:alpine
    restart: always
    env_file: stack.env
    volumes:
      - $BASE_PATH/db:/var/lib/postgresql/data
